FROM ruby:3.4-alpine

RUN apk add --update --no-cache build-base sqlite-dev git tzdata yaml-dev

WORKDIR /app

ADD . /app
RUN bundle install -j4 --retry 3

EXPOSE 3000
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
